@projeto_ruim_HostAddress = http://localhost:5189

GET {{projeto_ruim_HostAddress}}/weatherforecast/
Accept: application/json

###

@where = porto-alegre
@when = 2024-03-20

GET {{projeto_ruim_HostAddress}}/current-degrees/{{where}}?when={{when}}
Accept: application/json